client_id: 0
client_name: medical
data_path: data/processed/client0_medical.csv
model_dir: models/client0_medical
results_dir: results/label_private_splitfed/client0_medical
target_col: mortality
batch_size: 64
lr_encoder: 0.0001
weight_decay: 0.001
seed: 42
input_dim: 266
encoder_hidden_dim: 64
max_pos_weight: 5.0
