client_id: 5
client_name: cvicu
data_path: data/processed_n6/client5_cvicu.csv
model_dir: models/client5_cvicu
results_dir: results/label_private_splitfed/client5_cvicu
target_col: mortality
batch_size: 64
lr_encoder: 0.0001
weight_decay: 0.001
seed: 42
input_dim: 265
encoder_hidden_dim: 64
max_pos_weight: 5.0
